import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import ffmpegPath from 'ffmpeg-static';

const base = process.env.SMOKE_BASE_URL || 'http://localhost:3210';
async function json(path, body, token = '') {
  const response = await fetch(`${base}${path}`, { method: body ? 'POST' : 'GET', headers: { 'content-type': 'application/json', 'x-game-token': token }, body: body ? JSON.stringify(body) : undefined });
  const data = await response.json(); if (!response.ok) throw new Error(`${path}: ${JSON.stringify(data)}`); return data;
}
const generated = spawnSync(ffmpegPath, ['-hide_banner', '-loglevel', 'error', '-f', 'lavfi', '-i', 'sine=frequency=440:duration=15', '-b:a', '128k', '-f', 'mp3', 'pipe:1'], { maxBuffer: 2_000_000 });
assert.equal(generated.status, 0, generated.stderr?.toString());
const mediaToken = crypto.randomUUID(); const form = new FormData();
form.append('file', new Blob([new Uint8Array(generated.stdout)], { type: 'audio/mpeg' }), 'secret-title.mp3');
const uploadResponse = await fetch(`${base}/api/media/upload`, { method: 'POST', headers: { 'x-media-token': mediaToken }, body: form });
if (!uploadResponse.ok) throw new Error(`Upload: ${await uploadResponse.text()}`);
const { mediaUrl } = await uploadResponse.json();
assert.match(mediaUrl, /^asset:/);
const previewDenied = await fetch(`${base}/api/media/preview?asset=${mediaUrl}&start=3&duration=1`);
assert.equal(previewDenied.status, 403);
const preview = await fetch(`${base}/api/media/preview?asset=${mediaUrl}&start=3&duration=1`, { headers: { 'x-media-token': mediaToken } });
if (!preview.ok) throw new Error(`Preview: ${await preview.text()}`);
const bidQuestion = { prompt: 'Đoán âm thanh vòng 2', gameRound: 2, listenSeconds: 5, mediaType: 'uploaded_audio', mediaUrl, mediaStart: 3, primaryAnswer: 'A', acceptedAnswers: [], artist: '', hint: 'Âm đơn 440 Hz', revealMin: 1, revealMax: 10, revealStep: 1 };
const quiz = await json('/api/quiz', { title: `Smoke media ${Date.now()}`, description: '', visibility: 'private', questions: [{ ...bidQuestion, gameRound: 1, prompt: 'Đoán âm thanh vòng 1', hint: '' }, bidQuestion] });
const room = await json('/api/room', { action: 'create', quizId: quiz.id, ownerToken: quiz.ownerToken, nickname: 'Hosty' });
const guest = await json('/api/room', { action: 'join', pin: room.pin, nickname: 'Guest' });
await json('/api/command', { roomId: room.roomId, action: 'start' }, room.hostToken);
const openState = await json(`/api/state?roomId=${room.roomId}`, null, guest.playerToken);
assert.equal(openState.phase, 'OPEN_MEDIA_PLAYING');
assert.equal(openState.question.mediaUrl, mediaUrl);
const openClip = await fetch(`${base}/api/media/clip?roomId=${room.roomId}`, { headers: { 'x-game-token': guest.playerToken } });
assert.equal(openClip.status, 200);
assert.ok((await openClip.arrayBuffer()).byteLength > 10000);
await json('/api/command', { roomId: room.roomId, action: 'skipQuestion' }, room.hostToken);
await json('/api/command', { roomId: room.roomId, action: 'showScoreboard' }, room.hostToken);
await json('/api/command', { roomId: room.roomId, action: 'nextQuestion' }, room.hostToken);
assert.equal((await json(`/api/state?roomId=${room.roomId}`, null, guest.playerToken)).question.hint, 'Âm đơn 440 Hz');
await json('/api/command', { roomId: room.roomId, action: 'bid', value: 1 }, room.hostToken);
await json('/api/command', { roomId: room.roomId, action: 'bid', value: 2 }, guest.playerToken);
await new Promise(resolve => setTimeout(resolve, 3200));
const hostState = await json(`/api/state?roomId=${room.roomId}`, null, room.hostToken);
assert.equal(hostState.phase, 'MEDIA_PLAYING');
assert.equal(hostState.question.mediaUrl, mediaUrl);
assert.equal((await json(`/api/state?roomId=${room.roomId}`, null, guest.playerToken)).question.mediaUrl, undefined);
const denied = await fetch(`${base}/api/media/clip?roomId=${room.roomId}`, { headers: { 'x-game-token': guest.playerToken } });
assert.equal(denied.status, 403);
const clip = await fetch(`${base}/api/media/clip?roomId=${room.roomId}`, { headers: { 'x-game-token': room.hostToken } });
if (!clip.ok) throw new Error(`Clip: ${await clip.text()}`);
assert.match(clip.headers.get('content-type') || '', /audio\/mpeg/);
const bytes = Buffer.from(await clip.arrayBuffer());
assert.ok(bytes.length > 10000 && bytes.length < 100000, `Unexpected one-second clip size: ${bytes.length}`);
assert.equal(bytes.includes(Buffer.from('secret-title')), false);
console.log('Media smoke passed: shared round-one clip, pre-bid hint, and challenger-only one-second clip.');
