import assert from 'node:assert/strict';

const base = process.env.SMOKE_BASE_URL || 'http://localhost:3210';
async function call(path, body, token = '', method) {
  const response = await fetch(`${base}${path}`, { method: method || (body ? 'POST' : 'GET'), headers: { 'content-type': 'application/json', 'x-game-token': token, 'x-quiz-token': token }, body: body ? JSON.stringify(body) : undefined });
  const data = await response.json();
  if (!response.ok) throw new Error(`${path}: ${JSON.stringify(data)}`);
  return data;
}
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
async function state(roomId, token) { return call(`/api/state?roomId=${roomId}`, null, token); }
async function command(roomId, token, action, value) { return call('/api/command', { roomId, action, value }, token); }

const bidQuestion = { prompt: 'Tên bài hát?', gameRound: 2, topicKey: 'bid', listenSeconds: 5, answerSeconds: 12, mediaType: 'youtube', mediaUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', mediaStart: 1, primaryAnswer: 'Chúng Ta Của Hiện Tại', acceptedAnswers: [], artist: 'Sơn Tùng M-TP', hint: 'Một bài hát của Sơn Tùng M-TP', revealMin: 1, revealMax: 10, revealStep: 1 };
const openingQuestion = { ...bidQuestion, gameRound: 1, topicKey: 'open', mediaUrl: 'https://www.youtube.com/watch?v=jNQXAC9IVRw', mediaStart: 0, resultStart: 0, resultSeconds: 1, answerSeconds: 9, prompt: 'Bài hát vòng 1?', primaryAnswer: 'Bài hát khác', artist: 'Ca sĩ mở màn', hint: '' };
const quiz = await call('/api/quiz', { title: `Smoke ${Date.now()}`, description: 'Integration test', visibility: 'private', topics: [{ key: 'open', gameRound: 1, title: 'Mở màn', songCount: 1 }, { key: 'bid', gameRound: 2, title: 'Đấu giá', songCount: 1 }], questions: [openingQuestion, bidQuestion] });
await assert.rejects(call(`/api/quiz?id=${quiz.id}`), /chưa được chia sẻ/);
await assert.rejects(call('/api/room', { action: 'create', quizId: quiz.id, nickname: 'Anonymous' }), /riêng tư/);
await assert.rejects(call('/api/quiz', { id: quiz.id, visibility: 'unlisted' }, 'wrong-token', 'PATCH'), /không có quyền/);
await call('/api/quiz', { id: quiz.id, visibility: 'unlisted' }, quiz.ownerToken, 'PATCH');
const sharedQuiz = await call(`/api/quiz?id=${quiz.id}`);
assert.equal(sharedQuiz.title.startsWith('Smoke'), true);
assert.equal(sharedQuiz.questionCount, 2);
assert.equal(sharedQuiz.questions, undefined);
assert.equal(sharedQuiz.own, false);
assert.equal((await call('/api/quiz')).some(item => item.id === quiz.id), false);
const sharedRoom = await call('/api/room', { action: 'create', quizId: quiz.id, nickname: 'Anonymous' });
assert.equal((await state(sharedRoom.roomId, sharedRoom.hostToken)).players.length, 1);
const room = await call('/api/room', { action: 'create', quizId: quiz.id, ownerToken: quiz.ownerToken, nickname: 'Hosty', avatarId: 17 });
const joinToken = crypto.randomUUID();
const a = await call('/api/room', { action: 'join', pin: room.pin, nickname: 'Alpha', avatarId: 2, clientToken: joinToken });
const retriedA = await call('/api/room', { action: 'join', pin: room.pin, nickname: 'Alpha', avatarId: 2, clientToken: joinToken });
assert.equal(retriedA.playerId, a.playerId);
assert.equal(retriedA.playerToken, a.playerToken);
const b = await call('/api/room', { action: 'join', pin: room.pin, nickname: 'Beta', avatarId: 11 });
const c = await call('/api/room', { action: 'join', pin: room.pin, nickname: 'Gamma', avatarId: 20 });
const lobby = await state(room.roomId, room.hostToken);
assert.equal(lobby.players.length, 4);
assert.equal(lobby.me.nickname, 'Hosty');
assert.equal(lobby.isHost, true);
assert.deepEqual(lobby.players.map(p => p.colorIndex).sort(), [0, 1, 2, 3]);
assert.equal(lobby.players.find(p => p.nickname === 'Hosty').avatarId, 17);
assert.equal(lobby.players.find(p => p.nickname === 'Gamma').avatarId, 20);
await assert.rejects(call('/api/room', { action: 'join', pin: room.pin, nickname: 'Invalid', avatarId: 21 }), /không hợp lệ/);
await assert.rejects(call('/api/room', { action: 'join', pin: room.pin, nickname: 'Fifth' }), /Phòng đã đủ 4 người/);
const streamAbort = new AbortController();
const stream = await fetch(`${base}/api/events?roomId=${room.roomId}`, { headers: { 'x-game-token': a.playerToken }, signal: streamAbort.signal });
assert.equal(stream.status, 200);
const firstEvent = new TextDecoder().decode((await stream.body.getReader().read()).value);
assert.match(firstEvent, /data: \d+/);
streamAbort.abort();
await command(room.roomId, room.hostToken, 'start');
assert.equal((await state(room.roomId, a.playerToken)).phase, 'TOPIC_INTRO');
assert.equal((await state(room.roomId, a.playerToken)).topicName, 'Mở màn');
await sleep(3200);
const opening = await state(room.roomId, a.playerToken);
assert.equal(opening.gameRound, 1);
assert.equal(opening.phase, 'OPEN_MEDIA_PLAYING');
assert.equal(opening.question.mediaStart, 0);
assert.equal(opening.activeChallengerIds.length, 4);
assert.ok(opening.question.mediaUrl);
for (const playerToken of [room.hostToken, b.playerToken, c.playerToken]) {
  const shared = await state(room.roomId, playerToken);
  assert.ok(shared.activeChallengerIds.includes(shared.me.id));
  assert.equal(shared.question.mediaUrl, opening.question.mediaUrl);
  assert.equal(shared.question.mediaStart, opening.question.mediaStart);
}
const paused = await command(room.roomId, room.hostToken, 'pause');
assert.equal(paused.phase, 'OPEN_MEDIA_PLAYING');
assert.ok(paused.pausedAt);
await sleep(1200);
const stillPaused = await state(room.roomId, a.playerToken);
assert.equal(stillPaused.phase, 'OPEN_MEDIA_PLAYING');
assert.equal(stillPaused.phaseEndsAt, paused.phaseEndsAt);
await assert.rejects(command(room.roomId, room.hostToken, 'skipQuestion'), /đang tạm dừng/);
const resumed = await command(room.roomId, room.hostToken, 'resume');
assert.equal(resumed.pausedAt, null);
assert.ok(resumed.phaseEndsAt - paused.phaseEndsAt >= 1200);
await sleep(10200);
const openingAnswerPhase = await state(room.roomId, a.playerToken);
assert.equal(openingAnswerPhase.phase, 'OPEN_ANSWERING');
assert.equal(openingAnswerPhase.question.answerSeconds, 9);
assert.equal(openingAnswerPhase.phaseEndsAt - openingAnswerPhase.phaseStartedAt, 9000);
for (const playerToken of [room.hostToken, a.playerToken, b.playerToken, c.playerToken]) await command(room.roomId, playerToken, 'answer', 'Sai vòng 1');
assert.equal((await state(room.roomId, room.hostToken)).phase, 'OPEN_ANSWERING');
await command(room.roomId, room.hostToken, 'answer', 'Sai lần hai');
assert.equal((await state(room.roomId, room.hostToken)).myAttemptCount, 2);
await assert.rejects(command(room.roomId, room.hostToken, 'answer', 'Sai lần hai'), /đã thử đáp án này/);
await sleep(9200);
const openingResult = await state(room.roomId, room.hostToken);
assert.equal(openingResult.phase, 'ROUND_RESULT');
assert.equal(openingResult.question.resultStart, 0);
assert.equal(openingResult.question.resultSeconds, 1);
assert.equal(openingResult.question.primaryAnswer, 'Bài hát khác');
assert.equal(openingResult.question.artist, 'Ca sĩ mở màn');
assert.ok(openingResult.phaseEndsAt - openingResult.phaseStartedAt >= 7000);
await sleep(7200);
assert.equal((await state(room.roomId, a.playerToken)).phase, 'SCOREBOARD');
await sleep(4200);
assert.equal((await state(room.roomId, a.playerToken)).phase, 'TOPIC_INTRO');
assert.equal((await state(room.roomId, a.playerToken)).topicName, 'Đấu giá');
await sleep(3200);
assert.equal((await state(room.roomId, a.playerToken)).phase, 'BIDDING');
assert.equal((await state(room.roomId, room.hostToken)).gameRound, 2);
assert.equal((await state(room.roomId, a.playerToken)).question.hint, 'Một bài hát của Sơn Tùng M-TP');
await command(room.roomId, room.hostToken, 'bid', 2);
await command(room.roomId, a.playerToken, 'bid', 2);
const hidden = await state(room.roomId, b.playerToken);
assert.equal(hidden.players.find(p => p.nickname === 'Alpha').bid, undefined);
assert.equal(hidden.players.find(p => p.nickname === 'Hosty').bid, undefined);
await command(room.roomId, b.playerToken, 'bid', 3);
await command(room.roomId, c.playerToken, 'bid', 4);
assert.equal((await state(room.roomId, a.playerToken)).phase, 'BID_REVEAL');
await sleep(3200);
const first = await state(room.roomId, a.playerToken);
assert.equal(first.phase, 'MEDIA_PLAYING');
assert.equal(first.activeBid, 2);
assert.equal(first.activeChallengerIds.length, 2);
assert.ok(first.activeChallengerIds.includes(room.hostPlayerId));
assert.equal(first.question.primaryAnswer, undefined);
assert.ok((await state(room.roomId, room.hostToken)).question.mediaUrl);
assert.equal((await state(room.roomId, c.playerToken)).question.mediaUrl, undefined);
await sleep(7200);
assert.equal((await state(room.roomId, a.playerToken)).phase, 'ANSWERING');
await command(room.roomId, room.hostToken, 'answer', 'Sai từ host');
const hostWrong = await state(room.roomId, room.hostToken);
assert.equal(hostWrong.myAnswerCorrect, false);
assert.equal((await state(room.roomId, a.playerToken)).myAnswerCorrect, null);
assert.equal(hostWrong.players.find(p => p.nickname === 'Hosty').correct, undefined);
await assert.rejects(command(room.roomId, room.hostToken, 'answer', 'Sai lần hai'), /Vòng 2 chỉ được trả lời một lần/);
await command(room.roomId, a.playerToken, 'answer', 'Sai 1');
assert.equal((await state(room.roomId, a.playerToken)).myAttemptCount, 1);
const second = await state(room.roomId, b.playerToken);
assert.equal(second.phase, 'TURN_TRANSITION');
assert.equal(second.activeBid, 3);
assert.deepEqual(second.turnNotice.previousNames.sort(), ['Alpha', 'Hosty'].sort());
assert.deepEqual(second.turnNotice.nextNames, ['Beta']);
assert.equal(second.turnNotice.previousAllWrong, true);
assert.equal((await state(room.roomId, c.playerToken)).turnNotice.nextNames[0], 'Beta');
await sleep(3200);
assert.equal((await state(room.roomId, b.playerToken)).phase, 'MEDIA_PLAYING');
await sleep(8200);
assert.equal((await state(room.roomId, b.playerToken)).phase, 'ANSWERING');
await command(room.roomId, b.playerToken, 'answer', 'chung ta cua hien tai');
const result = await state(room.roomId, b.playerToken);
assert.equal(result.phase, 'ROUND_RESULT');
assert.equal(result.myAnswerCorrect, true);
assert.equal((await state(room.roomId, a.playerToken)).myAnswerCorrect, false);
assert.equal(result.question.primaryAnswer, 'Chúng Ta Của Hiện Tại');
assert.equal(result.question.artist, 'Sơn Tùng M-TP');
assert.equal(result.players.find(p => p.nickname === 'Beta').score, 800);
assert.equal(result.players.find(p => p.nickname === 'Hosty').score, 0);
assert.equal(result.players.find(p => p.nickname === 'Alpha').score, 0);
await sleep(10200);
assert.equal((await state(room.roomId, room.hostToken)).phase, 'SCOREBOARD');
await sleep(4200);
assert.equal((await state(room.roomId, room.hostToken)).phase, 'GAME_FINISHED');

const tiedRoom = await call('/api/room', { action: 'create', quizId: quiz.id, ownerToken: quiz.ownerToken, nickname: 'TieHost' });
const tiedA = await call('/api/room', { action: 'join', pin: tiedRoom.pin, nickname: 'TieAlpha' });
const tiedB = await call('/api/room', { action: 'join', pin: tiedRoom.pin, nickname: 'TieBeta' });
await command(tiedRoom.roomId, tiedRoom.hostToken, 'start');
await command(tiedRoom.roomId, tiedRoom.hostToken, 'skipQuestion');
await command(tiedRoom.roomId, tiedRoom.hostToken, 'showScoreboard');
await command(tiedRoom.roomId, tiedRoom.hostToken, 'nextQuestion');
assert.equal((await state(tiedRoom.roomId, tiedA.playerToken)).phase, 'TOPIC_INTRO');
await sleep(3200);
assert.equal((await state(tiedRoom.roomId, tiedA.playerToken)).phase, 'BIDDING');
await command(tiedRoom.roomId, tiedRoom.hostToken, 'bid', 2);
await command(tiedRoom.roomId, tiedA.playerToken, 'bid', 2);
await command(tiedRoom.roomId, tiedB.playerToken, 'bid', 2);
await sleep(3200);
assert.equal((await state(tiedRoom.roomId, tiedA.playerToken)).activeChallengerIds.length, 3);
await sleep(7200);
assert.equal((await state(tiedRoom.roomId, tiedA.playerToken)).phase, 'ANSWERING');
await command(tiedRoom.roomId, tiedRoom.hostToken, 'answer', 'Sai trước');
await assert.rejects(command(tiedRoom.roomId, tiedRoom.hostToken, 'answer', 'chung ta cua hien tai'), /Vòng 2 chỉ được trả lời một lần/);
await command(tiedRoom.roomId, tiedA.playerToken, 'answer', 'Chúng Ta Của Hiện Tại');
await command(tiedRoom.roomId, tiedB.playerToken, 'answer', 'chung ta cua hien tai');
const tiedResult = await state(tiedRoom.roomId, tiedRoom.hostToken);
assert.equal(tiedResult.phase, 'ROUND_RESULT');
assert.equal(tiedResult.players.find(p => p.nickname === 'TieHost').score, 0);
assert.equal(tiedResult.players.find(p => p.nickname === 'TieAlpha').score, 900);
assert.equal(tiedResult.players.find(p => p.nickname === 'TieBeta').score, 675);
assert.equal(tiedResult.players.find(p => p.nickname === 'TieAlpha').correctRank, 1);
assert.equal(tiedResult.players.find(p => p.nickname === 'TieBeta').correctRank, 2);
const revised = await call('/api/quiz', { id: quiz.id, ownerToken: quiz.ownerToken, title: 'Updated shared quiz', description: 'New version', visibility: 'unlisted', topics: [{ key: 'open', gameRound: 1, title: 'Mở màn', songCount: 1 }, { key: 'bid', gameRound: 2, title: 'Đấu giá', songCount: 1 }], questions: [openingQuestion, bidQuestion] });
assert.notEqual(revised.id, quiz.id);
assert.equal((await call(`/api/quiz?id=${quiz.id}`)).id, revised.id);
const redirectedRoom = await call('/api/room', { action: 'create', quizId: quiz.id, nickname: 'LinkVisitor' });
assert.equal((await state(redirectedRoom.roomId, redirectedRoom.hostToken)).quizTitle, 'Updated shared quiz');
console.log('Smoke test passed: private sharing, idempotent joining, stable links after edits, four-player play, and repeated guesses.');
