'use client';
import { useEffect, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { Suspense } from 'react';
import { ArrowDown, ArrowUp, Copy, Plus, Save, Trash2 } from 'lucide-react';
import { api, quizToken } from '@/lib/client';
import { ClipPlayer } from '@/components/ClipPlayer';
import { AudioClipPlayer } from '@/components/AudioClipPlayer';
import { youtubeId } from '@/lib/core';
import { formatStartTime, parseStartTime } from '@/lib/time';

type Question = { prompt: string; gameRound: 1 | 2; listenSeconds: number; answerSeconds: number; mediaType: 'youtube' | 'uploaded_audio'; mediaUrl: string; mediaStart: string; primaryAnswer: string; acceptedAnswers: string[]; artist: string; hint: string; revealMin: number; revealMax: number; revealStep: number };
const blank = (gameRound: 1 | 2 = 1): Question => ({ prompt: 'Đây là bài hát nào?', gameRound, listenSeconds: 5, answerSeconds: 12, mediaType: 'youtube', mediaUrl: '', mediaStart: '1', primaryAnswer: '', acceptedAnswers: [], artist: '', hint: '', revealMin: 1, revealMax: 10, revealStep: 1 });
const demo: Question[] = [
  { ...blank(1), prompt: 'Đây là bài hát Việt nào? (Mẫu 1)', mediaUrl: 'https://www.youtube.com/watch?v=REPLACE0001', mediaStart: '30', primaryAnswer: 'Bài hát mẫu 1', artist: 'Thay bằng nghệ sĩ thật' },
  { ...blank(1), prompt: 'Bạn nhận ra giai điệu này chứ? (Mẫu 2)', mediaUrl: 'https://www.youtube.com/watch?v=REPLACE0002', mediaStart: '45', primaryAnswer: 'Bài hát mẫu 2' },
  { ...blank(2), prompt: 'Đoán tên bài hát! (Mẫu 3)', mediaUrl: 'https://www.youtube.com/watch?v=REPLACE0003', mediaStart: '01:00', primaryAnswer: 'Bài hát mẫu 3', hint: 'Ca khúc có điệp khúc rất dễ nhận ra.' }
];
type QuizResponse = { title: string; description: string; visibility: 'private' | 'public'; own: boolean; usedInRoom: boolean; questions: Array<{ prompt: string; game_round: number; listen_seconds: number; answer_seconds: number; media_type: 'youtube' | 'uploaded_audio'; media_url: string; media_start: number; primary_answer: string; accepted_answers: string[]; artist: string; hint: string; reveal_min: number; reveal_max: number; reveal_step: number }> };
function Creator() {
  const router = useRouter(); const params = useSearchParams(); const editId = params.get('id');
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [visibility, setVisibility] = useState<'private' | 'public'>('private');
  const [questions, setQuestions] = useState<Question[]>([blank(1), blank(2)]); const [activeRound, setActiveRound] = useState<1 | 2>(1); const [selected, setSelected] = useState(0);
  const [previewDuration, setPreviewDuration] = useState(3); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [usedInRoom, setUsedInRoom] = useState(false);
  useEffect(() => {
    if (!editId) return;
    api<QuizResponse>(`/api/quiz?id=${encodeURIComponent(editId)}`, { token: quizToken(editId) }).then(quiz => {
      if (!quiz.own) throw new Error('Bạn không có quyền sửa bộ câu hỏi này.');
      setTitle(quiz.title); setDescription(quiz.description); setVisibility(quiz.visibility); setUsedInRoom(quiz.usedInRoom);
      const loaded = quiz.questions.map(q => ({ prompt: q.prompt, gameRound: q.game_round === 1 ? 1 as const : 2 as const, listenSeconds: q.listen_seconds || 5, answerSeconds: q.answer_seconds || 12, mediaType: q.media_type, mediaUrl: q.media_url, mediaStart: formatStartTime(q.media_start), primaryAnswer: q.primary_answer, acceptedAnswers: q.accepted_answers, artist: q.artist, hint: q.hint, revealMin: q.reveal_min, revealMax: q.reveal_max, revealStep: q.reveal_step }));
      setQuestions(loaded); setActiveRound(1); setSelected(loaded.findIndex(q => q.gameRound === 1));
    }).catch(e => setError(e.message));
  }, [editId]);
  const roundIndexes = questions.flatMap((item, index) => item.gameRound === activeRound ? [index] : []);
  const q = selected >= 0 && questions[selected]?.gameRound === activeRound ? questions[selected] : undefined;
  function update(patch: Partial<Question>) { setQuestions(previous => previous.map((item, index) => index === selected ? { ...item, ...patch } : item)); }
  function switchRound(round: 1 | 2) { setActiveRound(round); setSelected(questions.findIndex(item => item.gameRound === round)); }
  function add() { const insertAt = roundIndexes.length ? roundIndexes[roundIndexes.length - 1] + 1 : activeRound === 1 ? 0 : questions.length; setQuestions(previous => [...previous.slice(0, insertAt), blank(activeRound), ...previous.slice(insertAt)]); setSelected(insertAt); }
  function duplicate() { if (!q) return; setQuestions(previous => [...previous.slice(0, selected + 1), { ...q, acceptedAnswers: [...q.acceptedAnswers] }, ...previous.slice(selected + 1)]); setSelected(selected + 1); }
  function remove() { if (roundIndexes.length <= 1) return; const position = roundIndexes.indexOf(selected); setQuestions(previous => previous.filter((_, index) => index !== selected)); setSelected(position > 0 ? roundIndexes[position - 1] : roundIndexes[1] - 1); }
  function move(offset: number) { const position = roundIndexes.indexOf(selected); const target = roundIndexes[position + offset]; if (target === undefined) return; setQuestions(previous => { const next = [...previous]; [next[selected], next[target]] = [next[target], next[selected]]; return next; }); setSelected(target); }
  async function save(asCopy = false) {
    setError(''); setBusy(true);
    try {
      const normalizedQuestions = questions.map((item, index) => {
        const mediaStart = parseStartTime(item.mediaStart);
        if (mediaStart === null) throw new Error(`Vòng ${item.gameRound}, bài ${questions.slice(0, index + 1).filter(other => other.gameRound === item.gameRound).length}: thời điểm bắt đầu phải từ 1 giây; nhập số giây hoặc mm:ss.`);
        return { ...item, mediaStart };
      });
      const result = await api<{ id: string; ownerToken: string; replacedId?: string }>('/api/quiz', { method: 'POST', body: { id: editId && !asCopy ? editId : undefined, ownerToken: editId && !asCopy ? quizToken(editId) : undefined, title: asCopy ? `${title} (bản mới)` : title, description, visibility, questions: normalizedQuestions } });
      localStorage.setItem(`quiz:${result.id}`, result.ownerToken);
      const ids = JSON.parse(localStorage.getItem('myQuizzes') || '[]') as string[];
      if (result.replacedId) localStorage.removeItem(`quiz:${result.replacedId}`);
      localStorage.setItem('myQuizzes', JSON.stringify([...new Set([result.id, ...ids.filter(id => id !== result.replacedId)])]));
      router.push(`/quizzes?${result.replacedId ? 'updated' : 'created'}=${result.id}`);
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  return <main className="page"><div className="page-head"><div><span className="kicker">TẠO BỘ CÂU HỎI</span><h1>{editId ? 'Chỉnh sửa bộ câu hỏi' : 'Tạo bộ câu hỏi mới'}</h1><p>Chia bài hát thành vòng 1 nghe chung và vòng 2 đấu giá thời gian.</p></div><div className="editor-save-actions">{editId && <button className="button secondary big" onClick={() => save(true)} disabled={busy}>Lưu bản mới</button>}<button className="button primary big" onClick={() => save()} disabled={busy}><Save size={18} /> {busy ? 'Đang lưu…' : 'Lưu bộ câu hỏi'}</button></div></div>
    {error && <div className="notice error">{error}</div>}
    {editId && usedInRoom && <div className="notice info">Bộ câu hỏi đã được dùng trong phòng chơi. Khi lưu, hệ thống sẽ tạo bản đã sửa để các phòng cũ tiếp tục dùng nội dung trước đó.</div>}
    <section className="panel" style={{ marginBottom: 18 }}><div className="form-row"><div className="field"><label>Tên bộ câu hỏi *</label><input value={title} onChange={e => setTitle(e.target.value)} placeholder="Ví dụ: Đoán bài hát Việt" /></div><div className="field"><label>Hiển thị</label><select value={visibility} onChange={e => setVisibility(e.target.value as 'private' | 'public')}><option value="private">Riêng tư</option><option value="public">Công khai</option></select></div></div><div className="field" style={{ marginBottom: 0 }}><label>Mô tả</label><input value={description} onChange={e => setDescription(e.target.value)} placeholder="Một câu ngắn giới thiệu bộ câu hỏi" /></div><button className="button ghost" style={{ marginTop: 10, paddingLeft: 0 }} onClick={() => { setTitle('Đoán bài hát Việt'); setDescription('Bộ câu hỏi mẫu — thay đường dẫn YouTube và đáp án trước khi chơi.'); setQuestions(demo); setActiveRound(1); setSelected(0); }}>Dùng ba câu hỏi mẫu</button></section>
    <div className="round-tabs" role="tablist" aria-label="Vòng chơi">{([1, 2] as const).map(round => <button key={round} type="button" role="tab" id={`round-tab-${round}`} aria-controls="round-panel" aria-selected={activeRound === round} className={`round-tab ${activeRound === round ? 'active' : ''}`} onClick={() => switchRound(round)}><strong>Vòng {round}</strong><span>{round === 1 ? 'Cùng nghe và đoán' : 'Đấu giá thời gian'}</span><small>{questions.filter(item => item.gameRound === round).length} bài hát</small></button>)}</div>
    <div className="editor" role="tabpanel" id="round-panel" aria-labelledby={`round-tab-${activeRound}`}><aside className="panel editor-side"><h3>Bài hát vòng {activeRound} ({roundIndexes.length})</h3><p className="muted">{activeRound === 1 ? 'Mọi người cùng nghe đoạn nhạc và đoán tên bài hát.' : 'Người chơi xem gợi ý rồi đấu giá số giây muốn nghe.'}</p><div className="question-list">{roundIndexes.map((index, position) => <button key={index} type="button" className={`question-item ${index === selected ? 'active' : ''}`} onClick={() => setSelected(index)}>Bài {position + 1}<small>{questions[index].primaryAnswer || questions[index].prompt}</small></button>)}</div><button type="button" className="button secondary" onClick={add}><Plus size={16} /> Thêm bài hát</button></aside>
      <section className="panel">{!q ? <div className="round-empty"><h2>Chưa có bài hát cho vòng {activeRound}</h2><p>Thêm ít nhất một bài hát để lưu bộ câu hỏi và bắt đầu chơi.</p><button type="button" className="button primary" onClick={add}><Plus size={16} /> Thêm bài hát vòng {activeRound}</button></div> : <><div className="editor-toolbar"><h2>Vòng {activeRound} · Bài {roundIndexes.indexOf(selected) + 1}</h2><div><button title="Lên" aria-label="Đưa bài lên" className="button ghost" onClick={() => move(-1)} disabled={roundIndexes.indexOf(selected) === 0}><ArrowUp size={16} /></button><button title="Xuống" aria-label="Đưa bài xuống" className="button ghost" onClick={() => move(1)} disabled={roundIndexes.indexOf(selected) === roundIndexes.length - 1}><ArrowDown size={16} /></button><button title="Nhân bản" aria-label="Nhân bản bài" className="button ghost" onClick={duplicate}><Copy size={16} /></button><button title="Xóa" aria-label="Xóa bài" className="button danger" onClick={remove} disabled={roundIndexes.length <= 1}><Trash2 size={16} /></button></div></div>
        <div className="field"><label>Nội dung câu hỏi *</label><input value={q.prompt} onChange={e => update({ prompt: e.target.value })} /></div>
        {activeRound === 2 ? <div className="field"><label>Gợi ý trước khi đấu giá *</label><input value={q.hint} onChange={e => update({ hint: e.target.value })} maxLength={200} placeholder="Ví dụ: Ca khúc nhạc Việt phát hành sau năm 2020" /><small>Tất cả người chơi thấy gợi ý này trước khi chọn số giây.</small></div> : <div className="field"><label>Thời lượng nghe chung</label><select value={q.listenSeconds} onChange={e => update({ listenSeconds: Number(e.target.value) })}>{[3, 5, 7, 10].map(n => <option key={n} value={n}>{n} giây</option>)}</select><small>Tất cả người chơi nghe cùng đoạn rồi nhập tên bài hát.</small></div>}
        <div className="field"><label>Thời gian trả lời</label><select value={q.answerSeconds} onChange={e => update({ answerSeconds: Number(e.target.value) })}>{[5, 8, 10, 12, 15, 20, 30, 45, 60].map(n => <option key={n} value={n}>{n} giây</option>)}</select><small>Đếm ngược bắt đầu sau khi đoạn nhạc kết thúc; áp dụng cho bài này ở vòng {activeRound}.</small></div>
        <div className="form-row"><div className="field"><label>Loại câu hỏi</label><input value="Âm nhạc — đoán bài hát" disabled /></div><div className="field"><label>Nguồn nhạc</label><input value={q.mediaType === 'youtube' ? 'Video YouTube nhúng' : 'Tệp âm thanh từ bộ câu hỏi cũ'} disabled /></div></div>
        {q.mediaType === 'uploaded_audio' ? <div className="field"><div className="notice info">Câu hỏi cũ này đang dùng tệp âm thanh. Các câu hỏi mới chỉ dùng YouTube.</div><button type="button" className="button secondary" onClick={() => update({ mediaType: 'youtube', mediaUrl: '' })}>Chuyển sang YouTube</button></div> : <div className="field"><label>Đường dẫn YouTube *</label><input value={q.mediaUrl} onChange={e => update({ mediaUrl: e.target.value })} placeholder="https://www.youtube.com/watch?v=..." /><small>Hệ thống chỉ lưu đường dẫn và thời điểm bắt đầu. Người tạo có thể xem video gốc; trong phòng chơi, video được che để giữ bí mật đáp án.</small></div>}
        <div className="form-row"><div className="field"><label>Bắt đầu (giây hoặc mm:ss) *</label><input type="text" value={q.mediaStart} onChange={e => update({ mediaStart: e.target.value })} onBlur={() => { const seconds = parseStartTime(q.mediaStart); if (seconds !== null) update({ mediaStart: formatStartTime(seconds) }); }} placeholder="Ví dụ: 75 hoặc 01:15" aria-invalid={parseStartTime(q.mediaStart) === null} /><small>Tối thiểu 1 giây. Từ 60 giây, thời điểm sẽ hiện dạng phút:giây.</small></div><div className="field"><label>Thời lượng nghe thử</label><select value={previewDuration} onChange={e => setPreviewDuration(Number(e.target.value))}>{[1, 3, 5, 10].map(n => <option key={n} value={n}>{n} giây</option>)}</select></div></div>
        {q.mediaType === 'youtube' && youtubeId(q.mediaUrl) && parseStartTime(q.mediaStart) !== null && <ClipPlayer key={`${q.mediaUrl}-${q.mediaStart}-${previewDuration}`} url={q.mediaUrl} start={parseStartTime(q.mediaStart)!} duration={previewDuration} preview />}
        {q.mediaType === 'uploaded_audio' && q.mediaUrl.startsWith('asset:') && parseStartTime(q.mediaStart) !== null && <AudioClipPlayer key={`${q.mediaUrl}-${q.mediaStart}-${previewDuration}`} asset={q.mediaUrl} start={parseStartTime(q.mediaStart)!} duration={previewDuration} preview />}
        <div className="divider" /><div className="field"><label>Đáp án chính *</label><input value={q.primaryAnswer} onChange={e => update({ primaryAnswer: e.target.value })} placeholder="Tên bài hát" /></div><div className="field"><label>Đáp án chấp nhận thêm</label><textarea value={q.acceptedAnswers.join('\n')} onChange={e => update({ acceptedAnswers: e.target.value.split('\n') })} placeholder="Mỗi đáp án một dòng" /><small>Tự động bỏ qua chữ hoa, dấu câu và dấu tiếng Việt.</small></div><div className="field"><label>Nghệ sĩ (tuỳ chọn)</label><input value={q.artist} onChange={e => update({ artist: e.target.value })} /></div>
        {activeRound === 2 && <><div className="divider" /><h3>Thời gian đấu giá</h3><p className="muted">Số giây người chơi chọn quyết định độ dài đoạn nhạc được nghe.</p><div className="form-row three"><div className="field"><label>Nhỏ nhất</label><input type="number" min="1" value={q.revealMin} onChange={e => update({ revealMin: Number(e.target.value) })} /></div><div className="field"><label>Lớn nhất</label><input type="number" max="30" value={q.revealMax} onChange={e => update({ revealMax: Number(e.target.value) })} /></div><div className="field"><label>Bước</label><input type="number" min="1" value={q.revealStep} onChange={e => update({ revealStep: Number(e.target.value) })} /></div></div></>}
      </>}</section></div></main>;
}
export default function CreatePage() { return <Suspense fallback={<main className="page">Đang tải trang chỉnh sửa…</main>}><Creator /></Suspense>; }
