import Link from 'next/link';
import { ArrowUpRight, Headphones, LockKeyhole, Trophy, Zap } from 'lucide-react';
export default function Home() {
  return <main>
    <section className="hero shell"><div className="hero-copy"><div className="eyebrow"><span className="live-dot" /> TRÒ CHƠI 2–4 NGƯỜI</div><h1>Bạn cần <em>bao nhiêu giây</em> để đoán bài hát?</h1><p>Vòng 1 cùng nghe và đoán. Vòng 2, mỗi người chọn số giây muốn nghe; chọn ít hơn sẽ được trả lời trước và có cơ hội ghi nhiều điểm hơn.</p><div className="hero-actions"><Link className="button primary big" href="/join">Nhập mã phòng để chơi <ArrowUpRight size={19} /></Link><Link className="button secondary big" href="/create">Tạo bộ câu hỏi</Link></div><div className="hero-small"><span>✦ Chơi không cần tài khoản</span><span>✦ Chơi cùng bạn bè</span><span>✦ Mỗi giây đều đáng giá</span></div></div><div className="hero-card"><div className="card-top"><span className="card-label">ĐANG ĐẤU GIÁ</span><span className="card-counter">CÂU 03 / 10</span></div><div className="record-art"><div className="record-disc"><div className="record-center" /></div><span className="music-note">♫</span></div><h2>Đây là bài hát nào?</h2><div className="bid-mini"><span>1s</span><span className="selected">2s</span><span>3s</span><span>4s</span><span>5s</span></div><div className="card-bottom"><span>● ● ● ○</span><span>3/4 đã chốt thời gian</span></div></div></section>
    <section className="how shell"><div className="section-head"><span className="kicker">CÁCH CHƠI</span><h2>Hai vòng, hai cách nghe.</h2></div><div className="steps"><article><div className="step-icon"><Headphones size={25} /></div><span>01 / CÙNG NGHE</span><h3>Nghe và đoán</h3><p>Mọi người cùng nghe một đoạn nhạc ngắn rồi nhập tên bài hát.</p></article><article><div className="step-icon"><LockKeyhole size={25} /></div><span>02 / ĐẤU GIÁ</span><h3>Chọn số giây</h3><p>Ở vòng 2, mỗi người bí mật chọn số giây cần nghe. Người chọn ít nhất nghe trước.</p></article><article><div className="step-icon"><Trophy size={25} /></div><span>03 / GHI ĐIỂM</span><h3>Đoán đúng, ghi điểm</h3><p>Nếu người nghe trước trả lời sai, lượt nghe chuyển sang người tiếp theo.</p></article></div></section>
    <section className="bottom-cta shell"><div><Zap size={25} /><h2>Sẵn sàng thử tai nghe?</h2><p>Tạo bộ câu hỏi riêng, gửi mã phòng và bắt đầu chơi.</p></div><Link className="button light big" href="/create">Tạo bộ câu hỏi miễn phí <ArrowUpRight size={19} /></Link></section>
  </main>;
}
