'use client';
import { useEffect, useState, type CSSProperties } from 'react';
import Link from 'next/link';
import { Check, Lock, Trophy, X } from 'lucide-react';
import { ClueBoard } from './ClueBoard';
import { BrandMark } from './BrandMark';
import { PlayerAvatar } from './PlayerAvatar';
import { RankingBoard } from './RankingBoard';
import { PLAYER_COLORS } from '@/lib/playerAppearance';
import type { Clue, CluePhase } from '@/lib/clueRules';
export type ClueGameState={gameType:'SONG_CLUE';mixed?:boolean;isHost:boolean;gameRound:number;roundCount:number;pausedAt?:number|null;roomId:string;pin:string;quizTitle:string;phase:CluePhase;phaseStartedAt:number;phaseEndsAt:number|null;serverNow:number;lastEventId:number;questionIndex:number;questionCount:number;me:{id:string;nickname:string};players:Array<{id:string;nickname:string;avatarId:number;colorIndex:number;score:number;rank:number;ready:boolean;eliminated:boolean;connected:boolean;roundDelta:number}>;clue:{index:number;scores:number[];items:Clue[];value:number;votes:number;hasVoted:boolean;requiredVotes:number;holder:string|null;lockedScore:number;outcome:'correct'|'wrong'|'timeout'|null;eliminated:boolean};question:{id:string;primaryAnswer?:string;artist?:string;answerSeconds:number}};
export function RoomCountdown({end,serverNow}:{end:number|null;serverNow:number}){
  const [offset,setOffset]=useState(()=>serverNow-Date.now());const [clock,setClock]=useState(Date.now());
  useEffect(()=>{setOffset(serverNow-Date.now());setClock(Date.now());},[serverNow,end]);
  useEffect(()=>{const t=setInterval(()=>setClock(Date.now()),200);return()=>clearInterval(t);},[]);
  return end===null?null:<span className="timer" aria-label="Thời gian còn lại">{Math.max(0,Math.ceil((end-clock-offset)/1000))}s</span>;
}
export function ClueRoom({state,busy,error,command}:{state:ClueGameState;busy:boolean;error:string;command:(action:string,value?:string|number)=>Promise<void>}){
  const [answer,setAnswer]=useState('');const [pending,setPending]=useState('');const holder=state.players.find(p=>p.id===state.clue.holder);const me=state.players.find(p=>p.id===state.me.id)!;
  useEffect(()=>setAnswer(''),[state.questionIndex,state.clue.holder]);
  async function act(action:string,value?:string){if(busy||pending)return;setPending(action);try{await command(action,value);}finally{setPending('');}}
  const locked=busy||!!pending||state.pausedAt!=null;const canBuzz=state.phase==='CLUE_ACTIVE'&&!state.clue.eliminated;
  return <main className="game-room clue-room"><div className="game-topbar"><Link className="game-brand" href="/" aria-label="Về trang chủ"><BrandMark/></Link><span className="game-topbar-pin">MÃ PHÒNG <strong>{state.pin}</strong></span></div>
    <div className="game-content"><div className="page-head"><div><span className="kicker">ĐOÁN BÀI HÁT QUA GỢI Ý</span><h1>{state.quizTitle}</h1><p>{state.phase==='LOBBY'?'4 người · Tự động chơi khi tất cả sẵn sàng':`Vòng ${state.gameRound} · Câu ${state.questionIndex+1} / ${state.questionCount}`}</p></div><RoomCountdown end={state.pausedAt!=null?null:state.phaseEndsAt} serverNow={state.serverNow}/></div>
    <div className="clue-score-strip">{state.players.map(p=><div key={p.id} style={{'--player-color':PLAYER_COLORS[p.colorIndex]} as CSSProperties} className={`clue-mini-player ${p.id===state.me.id?'is-me':''} ${p.eliminated?'eliminated':''}`}><PlayerAvatar id={p.avatarId} size={34}/><span><strong>{p.nickname}</strong><small>{p.score.toLocaleString('vi-VN')} điểm</small></span>{p.eliminated&&<X size={14}/>}</div>)}</div>
    {state.mixed && state.isHost && <div className="host-actions"><button className="button secondary" disabled={busy} onClick={()=>act(state.pausedAt==null?'pause':'resume')}>{state.pausedAt==null?'Tạm dừng':'Tiếp tục'}</button><button className="button secondary" disabled={locked} onClick={()=>act('skipQuestion')}>Bỏ qua câu</button><button className="button danger" disabled={busy} onClick={()=>act('endGame')}>Kết thúc</button></div>}
    {state.pausedAt!=null&&<div className="notice info">Trò chơi đang tạm dừng.</div>}
    {error&&<div className="notice error" role="alert">{error}</div>}
    {state.phase==='LOBBY'&&<section className="panel center"><div className="room-pin">{state.pin}</div><p>Gửi mã phòng cho 3 người bạn. Mỗi người bấm sẵn sàng để tự bắt đầu.</p><p>{state.players.length}/4 người · {state.players.filter(p=>p.ready).length}/4 sẵn sàng</p><button className="button primary big full" disabled={locked||me.ready} onClick={()=>act('ready')}>{me.ready?'Đã sẵn sàng · Chờ bạn bè':pending==='ready'?'Đang xác nhận…':'Tôi đã sẵn sàng'}</button><Link className="button ghost" href="/join">Trang vào phòng</Link></section>}
    {state.phase==='QUESTION_INTRO'&&<section className="panel topic-intro"><span className="kicker">CÂU {state.questionIndex+1} / {state.questionCount}</span><h2>Bài hát bí ẩn</h2><p>{state.clue.scores.length} gợi ý từ khó đến dễ · Ai biết hãy giành quyền!</p></section>}
    {['CLUE_ACTIVE','CLUE_ANSWERING','CLUE_FEEDBACK'].includes(state.phase)&&<section className="panel clue-stage"><div className="clue-value"><span>BÀI HÁT BÍ ẨN</span><strong>{state.phase==='CLUE_ANSWERING'?state.clue.lockedScore:state.clue.value} <small>ĐIỂM</small></strong></div>
      <ClueBoard items={state.clue.items} index={state.clue.index} scores={state.clue.scores}/>
      {state.phase==='CLUE_ACTIVE'&&<>{state.clue.eliminated?<div className="notice error">Bạn đã trả lời sai hoặc hết giờ và không thể trả lời lại câu này. Tiếp tục theo dõi các bạn nhé.</div>:<div className="clue-actions"><button className="button primary clue-buzz" disabled={!canBuzz||locked} onClick={()=>act('buzz')}>{pending==='buzz'?'Đang tranh quyền…':'TÔI BIẾT!'}</button><button className="button secondary big full" disabled={locked||state.clue.hasVoted} onClick={()=>act('nextClue')}>{pending==='nextClue'?'Đang ghi nhận…':state.clue.hasVoted?'Đã bình chọn':state.clue.index===state.clue.scores.length-1?'XEM ĐÁP ÁN':'XEM GỢI Ý TIẾP'} · {state.clue.votes}/{state.clue.requiredVotes}</button><small>Cần {state.clue.requiredVotes} phiếu từ những người còn quyền trả lời.</small></div>}</>}
      {state.phase==='CLUE_ANSWERING'&&(state.clue.holder===state.me.id?<form onSubmit={e=>{e.preventDefault();void act('answer',answer);}} className="clue-answer-form"><h2>Bạn đã giành quyền!</h2><div className="field"><label htmlFor="clue-answer">Nhập tên bài hát</label><input id="clue-answer" autoFocus value={answer} onChange={e=>setAnswer(e.target.value)} maxLength={120} autoComplete="off" disabled={locked}/></div><button className="button primary big full" disabled={locked||!answer.trim()}>{pending==='answer'?'Đang chốt…':'CHỐT ĐÁP ÁN'}</button></form>:<div className="notice info clue-locked" role="status"><Lock size={24}/><strong>{holder?.nickname} đang trả lời…</strong></div>)}
      {state.phase==='CLUE_FEEDBACK'&&<div className="answer-feedback wrong" role="status"><X size={28}/><div><strong>{holder?.nickname} {state.clue.outcome==='timeout'?'đã hết thời gian':'trả lời chưa đúng'}</strong><span>{holder?.id===state.me.id?'Bạn không thể trả lời lại câu này.':'Những người còn quyền trả lời sẽ tiếp tục ở gợi ý kế tiếp.'}</span></div></div>}
    </section>}
    {state.phase==='CLUE_RESULT'&&<section className="panel center clue-result">{state.clue.outcome==='correct'?<><Check size={48}/><h2>CHÍNH XÁC!</h2><p>{holder?.nickname} <strong>+{state.clue.lockedScore} điểm</strong></p></>:<><h2>Đáp án đúng là</h2><p>Câu này chưa có người đoán đúng.</p></>}<div className="result-answer">{state.question.primaryAnswer}</div>{state.question.artist&&<p>{state.question.artist}</p>}<p className="muted">Tự chuyển câu sau ít giây.</p></section>}
    {state.phase==='GAME_FINISHED'&&<section className="panel"><div className="phase-banner"><Trophy size={32}/><h2>KẾT QUẢ</h2></div><p>{state.players.filter(p=>p.rank===1).map(p=>p.nickname).join(' và ')} {state.players.filter(p=>p.rank===1).length>1?'đồng hạng nhất!':'giành hạng nhất!'}</p><RankingBoard players={state.players} finished/><Link className="button secondary" href="/quizzes">Chọn bộ câu hỏi khác</Link></section>}
    </div></main>;
}
