'use client';
import { useState } from 'react';
import { ArrowDown, ArrowUp, X } from 'lucide-react';
import { CLUE_CATEGORIES, type Clue } from '@/lib/clueRules';
const labels:Record<string,string>={YEAR:'Năm phát hành',ARTIST:'Nghệ sĩ',MV:'MV',LYRIC:'Lời bài hát',TITLE_STRUCTURE:'Cấu trúc tên bài',EVENT:'Sự kiện',CAREER:'Sự nghiệp',TRIVIA:'Thông tin thú vị',KEYWORD:'Từ khóa',OTHER:'Khác'};
export const blankClues=():Clue[]=>[1000,800,600,400,200].map((score,i)=>({id:`clue-${i+1}`,text:'',score,category:'OTHER'}));
export const clueDemo=[
 {primaryAnswer:'Nơi Này Có Anh',artist:'Sơn Tùng M-TP',acceptedAnswers:['noi nay co anh'],clues:['Một ca khúc về tình yêu.','Người hát là một nam ca sĩ.','Nghệ sĩ có tên viết tắt M-TP.','Tên bài hát có bốn từ.','Hai từ cuối là “Có Anh”.']},
 {primaryAnswer:'Bông Hoa Đẹp Nhất',artist:'Quân A.P',acceptedAnswers:[],clues:['Một ca khúc pop Việt.','Tên bài hát gợi một hình ảnh thiên nhiên.','Người hát là Quân A.P.','Tên bài hát có bốn từ.','Tên bài bắt đầu bằng “Bông Hoa”.']},
 {primaryAnswer:'Một Nhà',artist:'Da LAB',acceptedAnswers:['mot nha'],clues:['Một ca khúc về sự gắn bó.','Bài hát do một nhóm nhạc thể hiện.','Nhóm nhạc là Da LAB.','Tên bài hát có hai từ.','Từ cuối trong tên bài là “Nhà”.']}
];
export function ClueFields({clues,seconds,onChange,onSeconds}:{clues:Clue[];seconds:number;onChange:(clues:Clue[])=>void;onSeconds:(value:number)=>void}){
 function move(i:number,d:number){const next=[...clues];[next[i],next[i+d]]=[next[i+d],next[i]];onChange(next);}
 return <><div className="field"><label>Thời gian mỗi gợi ý (giây)</label><input type="number" min={5} max={60} value={seconds} onChange={e=>onSeconds(Number(e.target.value))}/><small>Hết thời gian sẽ tự mở gợi ý tiếp theo. Người chơi cũng có thể bình chọn để mở sớm.</small></div><h3>5 gợi ý · từ khó đến dễ</h3>{clues.map((clue,i)=><div className="clue-editor-card" key={clue.id}><div className="clue-editor-top"><strong>Gợi ý {i+1}</strong><div><button type="button" className="button ghost" aria-label={`Đưa gợi ý ${i+1} lên`} disabled={i===0} onClick={()=>move(i,-1)}><ArrowUp size={16}/></button><button type="button" className="button ghost" aria-label={`Đưa gợi ý ${i+1} xuống`} disabled={i===4} onClick={()=>move(i,1)}><ArrowDown size={16}/></button></div></div><div className="field"><label>Nội dung gợi ý {i+1}</label><textarea value={clue.text} maxLength={500} onChange={e=>onChange(clues.map((c,j)=>j===i?{...c,text:e.target.value}:c))}/></div><div className="form-row"><div className="field"><label>Điểm</label><input type="number" min={1} max={10000} value={clue.score} onChange={e=>onChange(clues.map((c,j)=>j===i?{...c,score:Number(e.target.value)}:c))}/></div><div className="field"><label>Loại gợi ý</label><select value={clue.category} onChange={e=>onChange(clues.map((c,j)=>j===i?{...c,category:e.target.value as Clue['category']}:c))}>{CLUE_CATEGORIES.map(c=><option key={c} value={c}>{labels[c]}</option>)}</select></div></div></div>)}</>;
}
export function CluePreview({clues,title,artist,onClose}:{clues:Clue[];title:string;artist:string;onClose:()=>void}){const [index,setIndex]=useState(0);const [result,setResult]=useState(false);return <div className="clue-preview-modal" role="dialog" aria-modal="true" aria-label="Xem như người chơi"><section className="panel"><div className="phase-banner"><span className="kicker">XEM NHƯ NGƯỜI CHƠI</span><button type="button" className="button ghost" onClick={onClose} aria-label="Đóng xem trước"><X/></button></div>{result?<><div className="result-answer">{title||'Chưa nhập đáp án'}</div><p>{artist}</p><button type="button" className="button secondary" onClick={()=>{setResult(false);setIndex(0);}}>Xem lại</button></>:<><div className="clue-value"><span>BÀI HÁT BÍ ẨN</span><strong>{clues[index].score} điểm</strong></div>{clues.slice(0,index+1).map((c,i)=><article className={`clue-card ${i===index?'current':''}`} key={c.id}><span>GỢI Ý {i+1}</span><p>{c.text||'Gợi ý sẽ hiển thị ở đây.'}</p></article>)}<button type="button" className="button primary clue-buzz" onClick={()=>setResult(true)}>TÔI BIẾT!</button><button type="button" className="button secondary big full" onClick={()=>index===4?setResult(true):setIndex(index+1)}>{index===4?'Xem đáp án':'Xem gợi ý tiếp'}</button><p className="muted">Đây là bản xem trước bố cục; luật tranh quyền được kiểm tra trong phòng chơi.</p></>}</section></div>;}
