'use client';
import { useEffect, useRef, useState, type CSSProperties } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { ArrowRight, Check, Clock3, Headphones, Maximize2, Minimize2, Pause, Play, Trophy, Users, Volume2, VolumeX, X } from 'lucide-react';
import { api, gameToken } from '@/lib/client';
import { ClipPlayer } from './ClipPlayer';
import { NarrationControl } from './NarrationControl';
import { AudioClipPlayer } from './AudioClipPlayer';
import { RankingBoard } from './RankingBoard';
import { PlayerAvatar } from './PlayerAvatar';
import { BrandMark } from './BrandMark';
import { PLAYER_COLORS } from '@/lib/playerAppearance';
import { useRoomState } from '@/lib/useRoomState';
import { useGameSounds } from '@/lib/useGameSounds';
import { ClueRoom, type ClueGameState } from './ClueRoom';
import { modeDescription } from '@/lib/quizCategory';
import { scoreForBid, scoreForTimedAnswer, type Phase } from '@/lib/core';

type RoomPlayer = { id: string; nickname: string; avatarId: number; colorIndex: number; score: number; connected: boolean; bidLocked: boolean; bid?: number | null; autoBid?: boolean; answerLocked: boolean; answer?: string | null; correct?: boolean; correctRank?: number; roundDelta?: number };
const playerStyle = (player: RoomPlayer) => ({ '--player-color': PLAYER_COLORS[player.colorIndex] ?? PLAYER_COLORS[0] }) as CSSProperties;
type GameState = { category?:'FILM'|'MUSIC'; gameType: string; lastEventId: number; serverNow: number; roomId: string; pin: string; phase: Phase; phaseStartedAt: number; phaseEndsAt: number | null; pausedAt: number | null; questionIndex: number; questionCount: number; gameRound: number; playMode: 'OPEN'|'BID'|'CLUE'; roundCount: number; nextGameRound: number | null; roundQuestionIndex: number; roundQuestionCount: number; topicName: string; topicQuestionIndex: number; topicQuestionCount: number; quizTitle: string; question: { id: string; prompt: string; revealUnit: string; revealMin: number; revealMax: number; revealStep: number; mediaType: 'youtube' | 'uploaded_audio'; mediaUrl?: string; mediaStart?: number; resultStart?: number | null; resultSeconds?: number | null; listenSeconds: number; answerSeconds: number; bidSeconds: number; primaryAnswer?: string; artist?: string; hint?: string }; activeBid: number | null; activeChallengerIds: string[]; turnNotice: { previousNames: string[]; nextNames: string[]; previousAllWrong: boolean; nextBid: number } | null; players: RoomPlayer[]; me: { id: string; nickname: string } | null; isHost: boolean; myBid: number | null; myAnswerCorrect: boolean | null; myAnswer: string | null; myAttemptCount: number };
const names = (state: GameState) => state.players.filter(p => state.activeChallengerIds.includes(p.id)).map(p => p.nickname).join(' và ');
const phaseName: Record<Phase, string> = { LOBBY: 'Phòng chờ', TOPIC_INTRO: 'Chủ đề mới', OPEN_MEDIA_PLAYING: 'Cùng nghe nhạc', OPEN_ANSWERING: 'Cùng trả lời', BIDDING: 'Đấu giá', BID_REVEAL: 'Công bố thời gian', TURN_TRANSITION: 'Chuyển lượt', MEDIA_PLAYING: 'Nghe nhạc', ANSWERING: 'Trả lời', ROUND_RESULT: 'Kết quả', SCOREBOARD: 'Bảng điểm', GAME_FINISHED: 'Kết thúc' };
function Countdown({ end, pausedAt, serverNow }: { end: number | null; pausedAt?: number | null; serverNow: number }) { const [seconds, setSeconds] = useState(0); useEffect(() => { const offset = serverNow - Date.now(); const update = () => setSeconds(end ? Math.max(0, Math.ceil((end - (pausedAt ?? Date.now() + offset)) / 1000)) : 0); update(); const timer = setInterval(update, 150); return () => clearInterval(timer); }, [end, pausedAt, serverNow]); return end ? <span className={`timer ${seconds <= 5 ? 'urgent' : ''}`} aria-label={`Còn ${seconds} giây`}>{seconds}s</span> : null; }
function PhaseProgress({ start, end, pausedAt, serverNow, maxPoints }: { start: number; end: number | null; pausedAt: number | null; serverNow: number; maxPoints?: number }) {
  const [time, setTime] = useState(() => Date.now());
  const [offset, setOffset] = useState(() => serverNow - Date.now());
  useEffect(() => { setOffset(serverNow - Date.now()); setTime(Date.now()); }, [start, serverNow]);
  useEffect(() => { if (pausedAt !== null) return; const timer = setInterval(() => setTime(Date.now()), 100); return () => clearInterval(timer); }, [pausedAt]);
  if (end === null) return null;
  const clock = pausedAt ?? time + offset;
  const remaining = Math.max(0, end - clock);
  const total = Math.max(1, end - start);
  const percent = Math.min(100, remaining / total * 100);
  const points = maxPoints === undefined ? null : scoreForTimedAnswer(maxPoints, start, end, clock);
  return <div className="game-point-timer"><div className={`game-timer-track ${percent < 20 ? 'urgent' : ''}`} role="progressbar" aria-label={points === null ? 'Thời gian còn lại' : 'Điểm còn có thể nhận'} aria-valuemin={0} aria-valuemax={points === null ? 100 : maxPoints} aria-valuenow={points === null ? Math.round(percent) : points}><span style={{ width: `${percent}%` }} /></div>{points !== null && <div className="game-point-timer-label"><span>Điểm tối đa nếu trả lời đúng ngay</span><strong>{points.toLocaleString('vi-VN')} điểm</strong></div>}</div>;
}
export function GameRoom({ kind }: { kind: 'host' | 'player' }) {
  const params = useParams<{ roomId: string }>(); const roomId = params.roomId;
  const token = gameToken(roomId, kind);
  const {state,setState,error,setError} = useRoomState<GameState>(roomId,token); const [busy,setBusy]=useState(false); const [pendingAction,setPendingAction]=useState('');
  const [selectedBid, setSelectedBid] = useState<number | null>(null); const [answer, setAnswer] = useState('');
  const answerInputRef = useRef<HTMLInputElement>(null);
  const { enabled: soundsEnabled, toggle: toggleSounds, play: playSound } = useGameSounds();
  const soundState = useRef<{ question: number; attempts: number; phase: Phase } | null>(null);
  const clockState = useRef<{ key: string; second: number }>({ key: '', second: Infinity });
  const [fullscreen, setFullscreen] = useState(false);
  useEffect(() => { const sync = () => setFullscreen(!!document.fullscreenElement); document.addEventListener('fullscreenchange', sync); return () => document.removeEventListener('fullscreenchange', sync); }, []);
  useEffect(() => { setSelectedBid(null); setAnswer(''); }, [state?.questionIndex]);
  useEffect(() => {
    if (!busy && state?.phase === 'OPEN_ANSWERING' && state.playMode === 'OPEN' && state.myAttemptCount > 0 && state.myAnswerCorrect === false) {
      answerInputRef.current?.focus();
    }
  }, [busy, state?.phase, state?.playMode, state?.myAttemptCount, state?.myAnswerCorrect]);
  useEffect(() => {
    if (!state || state.gameType === 'SONG_CLUE') return;
    const previous = soundState.current;
    soundState.current = { question: state.questionIndex, attempts: state.myAttemptCount, phase: state.phase };
    if (!previous || previous.question !== state.questionIndex) return;
    if (state.myAttemptCount > previous.attempts) playSound(state.myAnswerCorrect ? 'correct' : 'wrong');
    if (previous.phase !== state.phase && state.phase === 'ROUND_RESULT' && state.players.some(player => (player.roundDelta ?? 0) > 0)) playSound('score');
    if (previous.phase !== state.phase && state.phase === 'SCOREBOARD') playSound('rank');
    if (previous.phase !== state.phase && state.phase === 'BID_REVEAL') playSound('reveal');
    if (previous.phase !== state.phase && ['TOPIC_INTRO', 'TURN_TRANSITION'].includes(state.phase)) playSound('transition');
  }, [state, playSound]);
  useEffect(() => {
    if (!state || state.gameType === 'SONG_CLUE' || state.phaseEndsAt === null || state.pausedAt !== null || !['BIDDING', 'OPEN_ANSWERING', 'ANSWERING', 'TURN_TRANSITION'].includes(state.phase)) return;
    const key = `${state.questionIndex}:${state.phase}:${state.phaseStartedAt}`;
    if (clockState.current.key !== key) clockState.current = { key, second: Infinity };
    const offset = state.serverNow - Date.now();
    const update = () => {
      const second = Math.max(0, Math.ceil((state.phaseEndsAt! - Date.now() - offset) / 1000));
      const previous = clockState.current.second;
      if (second === previous) return;
      clockState.current.second = second;
      if (second >= 1 && second <= 5 && second < previous) playSound(second === 1 ? 'finalTick' : 'tick');
      else if (state.phase === 'BIDDING' && second > 5 && second % 5 === 0 && second < previous) playSound('clock');
    };
    update();
    const timer = setInterval(update, 150);
    return () => clearInterval(timer);
  }, [state, playSound]);
  async function command(action: string, value?: string | number) {
    if (!token) return;
    setError(''); setBusy(true); setPendingAction(action);
    try { if (action === 'answer') playSound('submit'); setState(await api<GameState>('/api/command', { method: 'POST', token, body: { roomId, action, value }, signal: AbortSignal.timeout(12000) })); if (action === 'answer') setAnswer(''); }
    catch (e) { setError((e as Error).message); } finally { setBusy(false); setPendingAction(''); }
  }
  async function toggleFullscreen() { try { if (document.fullscreenElement) await document.exitFullscreen(); else await document.querySelector('.game-room')?.requestFullscreen(); } catch { setError('Không thể mở toàn màn hình trên trình duyệt này.'); } }
  if (!state) return <main className="page narrow"><div className="panel center">{error || 'Đang kết nối phòng chơi…'}</div></main>;
  if (state.gameType === 'SONG_CLUE') return <ClueRoom state={state as unknown as ClueGameState} busy={busy} error={error} command={command} />;
  const film = state.category === 'FILM';
  const watch = film ? 'XEM' : 'NGHE';
  const challenger = !!state.me && state.activeChallengerIds.includes(state.me.id);
  const canListen = !!state.me && (state.playMode === 'OPEN' || challenger);
  const canAnswer = !!state.me && (state.playMode === 'OPEN' || challenger);
  const locked = state.players.filter(p => p.bidLocked).length;
  const answered = state.players.filter(p => state.activeChallengerIds.includes(p.id) && p.answerLocked).length;
  const resultVideoOnly = state.phase === 'ROUND_RESULT' && state.question.mediaType === 'youtube' && !!state.question.mediaUrl;
  const answerMaxPoints = ['OPEN_ANSWERING', 'ANSWERING'].includes(state.phase) ? state.playMode === 'OPEN' ? 500 : state.activeBid === null ? undefined : scoreForBid(state.activeBid, state.question.revealMin, state.question.revealMax, state.question.revealStep) : undefined;
  return <main className={`game-room ${resultVideoOnly ? 'result-only' : ''}`}>
    <div className="game-topbar"><Link className="game-brand" href="/" aria-label="Đọ Nhạc — về trang chủ"><BrandMark /></Link><div className="game-topbar-meta"><span className="game-topbar-pin">MÃ PHÒNG <strong>{state.pin}</strong></span><span className="game-topbar-count"><Users size={16} /> {state.players.length}/4 người chơi</span><button type="button" className="game-icon-button" title={soundsEnabled ? 'Tắt âm thanh hiệu ứng' : 'Bật âm thanh hiệu ứng'} aria-label={soundsEnabled ? 'Tắt âm thanh hiệu ứng' : 'Bật âm thanh hiệu ứng'} aria-pressed={soundsEnabled} onClick={toggleSounds}>{soundsEnabled ? <Volume2 size={18} /> : <VolumeX size={18} />}</button>{kind === 'host' && !['LOBBY', 'GAME_FINISHED'].includes(state.phase) && <button type="button" className="game-icon-button" title={state.pausedAt === null ? 'Tạm dừng trò chơi' : 'Tiếp tục trò chơi'} aria-label={state.pausedAt === null ? 'Tạm dừng trò chơi' : 'Tiếp tục trò chơi'} disabled={busy} onClick={() => command(state.pausedAt === null ? 'pause' : 'resume')}>{state.pausedAt === null ? <Pause size={18} /> : <Play size={18} />}</button>}<button type="button" className="game-icon-button" title={fullscreen ? 'Thoát toàn màn hình' : 'Mở toàn màn hình'} aria-label={fullscreen ? 'Thoát toàn màn hình' : 'Mở toàn màn hình'} onClick={toggleFullscreen}>{fullscreen ? <Minimize2 size={18} /> : <Maximize2 size={18} />}</button></div></div>
    <div className="game-content"><div className="page-head game-heading"><div><span className="kicker">{kind === 'host' ? 'BẠN LÀ NGƯỜI TẠO PHÒNG' : `XIN CHÀO, ${state.me?.nickname?.toUpperCase()}`}</span><h1>{state.quizTitle}</h1><p>{state.phase === 'LOBBY' ? `Phòng chờ · ${state.roundCount} vòng chơi` : `Vòng ${state.gameRound} · Câu ${state.roundQuestionIndex} / ${state.roundQuestionCount}`}</p></div><span className="phase-pill">{film?phaseName[state.phase].replace('Cùng nghe nhạc','Cùng xem phim').replace('Nghe nhạc','Xem phim'):phaseName[state.phase]}</span></div>
    <div className="game-progress" aria-label={`Câu ${state.questionIndex + 1} trên ${state.questionCount}`}>{Array.from({ length: state.questionCount }, (_, index) => <span key={index} className={index < state.questionIndex ? 'done' : index === state.questionIndex ? 'current' : ''} />)}</div>
    {state.phase !== 'LOBBY' && <div className="game-topic-label"><span>VÒNG {state.gameRound} · CHỦ ĐỀ</span><strong>{state.topicName}</strong><small>Bài {state.topicQuestionIndex}/{state.topicQuestionCount}</small></div>}
    <PhaseProgress start={state.phaseStartedAt} end={state.phaseEndsAt} pausedAt={state.pausedAt} serverNow={state.serverNow} maxPoints={answerMaxPoints} />
    <NarrationControl roomId={roomId} token={token} questionId={state.question.id} paused={state.pausedAt!=null} prepare={state.phase!=='LOBBY'} kind={['BIDDING','BID_REVEAL','OPEN_ANSWERING','ANSWERING'].includes(state.phase)?'question':['ROUND_RESULT','SCOREBOARD','GAME_FINISHED'].includes(state.phase)?'answer':undefined}/>
    {error && <div className="notice error">{error}</div>}
    {state.pausedAt !== null && <div className="game-pause-overlay" role="status"><div className="game-pause-card"><Pause size={42} /><h2>Trò chơi đang tạm dừng</h2><p>Đồng hồ và đoạn nhạc sẽ tiếp tục khi người tạo phòng bấm tiếp tục.</p>{kind === 'host' && <button type="button" className="button primary big" disabled={busy} onClick={() => command('resume')}><Play size={18} /> Tiếp tục trò chơi</button>}</div></div>}
    {['OPEN_ANSWERING', 'ANSWERING'].includes(state.phase) && state.myAnswer !== null && state.myAnswerCorrect !== null && <div className={`answer-feedback ${state.myAnswerCorrect ? 'correct' : 'wrong'}`} role="status">{state.myAnswerCorrect ? <Check size={26} /> : <X size={26} />}<div><strong>{state.myAnswerCorrect ? 'Trả lời đúng!' : state.playMode === 'OPEN' ? 'Chưa đúng, thử tiếp nhé' : 'Trả lời sai'}</strong><span>{state.myAnswerCorrect ? 'Đáp án đã được chốt. Chờ kết quả của lượt này.' : state.playMode === 'OPEN' ? `Bạn đã thử ${state.myAttemptCount} lần. Hãy nhập đáp án khác trước khi hết giờ.` : film?'Bạn đã dùng lượt trả lời duy nhất. Chờ người xem tiếp theo hoặc kết quả.':'Bạn đã dùng lượt trả lời duy nhất. Chờ người nghe tiếp theo hoặc kết quả.'}</span></div></div>}
    <div className="room-layout"><div className="room-main">
      {state.phase === 'TOPIC_INTRO' && <div className="panel topic-intro" role="status"><span className="phase-pill">VÒNG {state.gameRound} · CHỦ ĐỀ MỚI</span><h2>{state.topicName}</h2><p>{state.topicQuestionCount} {film?'câu phim':'bài hát'} · {modeDescription(state.playMode,film)}</p><Countdown end={state.phaseEndsAt} pausedAt={state.pausedAt} serverNow={state.serverNow} /></div>}
      {state.phase === 'LOBBY' && <div className="panel">{kind === 'host' ? <><span className="kicker">GỬI MÃ PHÒNG NÀY CHO BẠN BÈ</span><div className="room-pin">{state.pin}</div><p className="subtitle">Mọi người vào <b>/join</b>, nhập mã phòng và tên hiển thị. Cần ít nhất 2 người để bắt đầu.</p><button className="button secondary" style={{ marginTop: 15 }} onClick={() => navigator.clipboard.writeText(`${location.origin}/join — Mã phòng ${state.pin}`)}>Sao chép lời mời</button></> : <><div className="waiting-art"><Users size={38} /></div><h2 className="center">Đã vào phòng!</h2><p className="center subtitle">Chờ người tạo phòng bắt đầu. Mã phòng: <b>{state.pin}</b></p></>}
        <div className="divider" /><p className="countline">{state.players.length}/4 người chơi đã vào phòng. Danh sách hiển thị bên phải.</p>{kind === 'host' && <button className="button primary big full" style={{ marginTop: 24 }} disabled={busy || state.players.length < 2} onClick={() => command('start')}>Bắt đầu vòng 1 <ArrowRight size={18} /></button>}</div>}
      {state.phase === 'BIDDING' && <div className="panel"><div className="phase-banner"><div><span className="phase-pill">ĐẤU GIÁ BÍ MẬT</span><h2>{state.question.prompt}</h2></div><Countdown end={state.phaseEndsAt} pausedAt={state.pausedAt} serverNow={state.serverNow} /></div><div className="hint-card"><span>GỢI Ý TRƯỚC KHI ĐẤU GIÁ</span><strong>{state.question.hint?.trim() || 'Người tạo chưa thêm gợi ý cho câu này.'}</strong></div><p className="subtitle">{film?'Bạn cần xem bao nhiêu giây để đoán?':'Bạn cần nghe bao nhiêu giây để đoán?'}</p>
        {state.me ? <>{state.myBid !== null ? <div className="center" style={{ padding: '32px 0' }}><div className="big-number">{state.myBid}s</div><h2>Đã khóa lựa chọn</h2><p className="subtitle">Chờ người chơi khác…</p></div> : <><div className="bid-options">{Array.from({ length: Math.floor((state.question.revealMax - state.question.revealMin) / state.question.revealStep) + 1 }, (_, i) => state.question.revealMin + i * state.question.revealStep).map(amount => <button key={amount} className={`bid-option ${selectedBid === amount ? 'active' : ''}`} onClick={() => setSelectedBid(amount)}>{amount}s</button>)}</div><button className="button primary big full" disabled={busy || selectedBid === null} onClick={() => command('bid', selectedBid!)}>Chốt {selectedBid ? `${selectedBid} giây` : 'thời gian'} <Check size={18} /></button></>}</> : <div className="notice info">Lựa chọn được giữ kín cho tới khi hết giờ hoặc mọi người đã chốt.</div>}
        <div className="countline"><LockProgress count={locked} total={state.players.length} /></div></div>}
      {state.phase === 'BID_REVEAL' && <div className="panel"><div className="phase-banner"><div><span className="phase-pill">CÔNG BỐ THỜI GIAN</span><h2>{film?'Ai chọn xem ít nhất?':'Ai chọn nghe ít nhất?'}</h2></div><Countdown end={state.phaseEndsAt} pausedAt={state.pausedAt} serverNow={state.serverNow} /></div><div className="bid-reveal-list">{[...state.players].sort((a, b) => Number(a.bid) - Number(b.bid)).map(p => <div className="reveal-row" key={p.id} style={playerStyle(p)}><span className="reveal-player"><PlayerAvatar id={p.avatarId} size={38} />{p.nickname}{p.autoBid ? ' (tự động)' : ''}</span><strong>{p.bid}s</strong></div>)}</div><p className="subtitle">Nhóm chọn ít giây nhất sẽ {film?'xem':'nghe'} trước. Nếu nhiều người trả lời đúng, người gửi đáp án trước được nhiều điểm hơn.</p></div>}
      {state.phase === 'TURN_TRANSITION' && <div className="panel center"><span className="phase-pill">CHUYỂN LƯỢT {watch}</span><div className="waiting-art"><Headphones size={39} /></div><h2>{state.turnNotice?.previousAllWrong ? `${state.turnNotice.previousNames.join(' và ')} đã trả lời sai` : film?'Nhóm vừa xem chưa có đáp án đúng':'Nhóm vừa nghe chưa có đáp án đúng'}</h2><p className="subtitle">Tiếp theo, <b>{state.turnNotice?.nextNames.join(' và ') || names(state)}</b> sẽ {film?'xem':'nghe'} {state.turnNotice?.nextBid ?? state.activeBid} giây.</p><p className="countline">Bắt đầu sau <Countdown end={state.phaseEndsAt} pausedAt={state.pausedAt} serverNow={state.serverNow} /></p></div>}
      {(state.phase === 'OPEN_MEDIA_PLAYING' || state.phase === 'MEDIA_PLAYING') && <div className="panel"><div className="phase-banner"><div><span className="phase-pill">{state.playMode === 'OPEN' ? `VÒNG ${state.gameRound} · CÙNG ${watch} ${state.question.listenSeconds} GIÂY` : `VÒNG ${state.gameRound} · ${watch} ${state.activeBid} GIÂY`}</span><h2>{state.question.prompt}</h2></div><Countdown end={state.phaseEndsAt} pausedAt={state.pausedAt} serverNow={state.serverNow} /></div><p className="subtitle">{state.playMode === 'OPEN' ? film?'Tất cả người chơi cùng xem và đoán.':'Tất cả người chơi cùng nghe và đoán.' : <><b>{names(state)}</b> {film?'đang xem phim.':'đang nghe nhạc.'}</>}</p>{state.turnNotice && <div className="notice info">{state.turnNotice.previousNames.join(' và ')} chưa trả lời đúng. Lượt {film?'xem':'nghe'} tiếp theo thuộc về <b>{state.turnNotice.nextNames.join(' và ')}</b>.</div>}{canListen ? <><div className="notice info">{film?'Đoạn phim sẽ tự phát khi sẵn sàng.':'Đoạn nhạc sẽ tự phát khi sẵn sàng.'} Nếu trình duyệt chặn tự phát, hãy bấm nút phát.</div>{state.question.mediaUrl && (state.question.mediaType === 'uploaded_audio' ? <AudioClipPlayer key={`${state.questionIndex}-${state.activeBid ?? 'open'}`} asset={state.question.mediaUrl} start={Number(state.question.mediaStart)} duration={state.playMode === 'OPEN' ? Number(state.question.listenSeconds) : Number(state.activeBid)} roomId={roomId} gameToken={token} paused={state.pausedAt !== null} /> : <ClipPlayer key={`${state.questionIndex}-${state.activeBid ?? 'open'}`} url={state.question.mediaUrl} start={Number(state.question.mediaStart)} showVideo={film} duration={state.playMode === 'OPEN' ? Number(state.question.listenSeconds) : Number(state.activeBid)} paused={state.pausedAt !== null} />)}</> : <div className="waiting-art"><Headphones size={39} /></div>}</div>}
      {(state.phase === 'OPEN_ANSWERING' || state.phase === 'ANSWERING') && <div className="panel"><div className="phase-banner"><div><span className="phase-pill">VÒNG {state.gameRound} · TRẢ LỜI</span><h2>{film?'Tên phim là gì?':'Tên bài hát là gì?'}</h2></div><Countdown end={state.phaseEndsAt} pausedAt={state.pausedAt} serverNow={state.serverNow} /></div><p className="muted">{state.playMode === 'OPEN' ? `Bạn có thể thử nhiều đáp án trong ${state.question.answerSeconds} giây. Đúng sẽ chốt lượt.` : `Bạn chỉ được gửi một đáp án trong ${state.question.answerSeconds} giây.`}</p>{state.activeChallengerIds.length > 1 && <div className="notice info">Đáp án đúng gửi lên hệ thống sớm hơn sẽ được nhiều điểm hơn.</div>}{canAnswer ? state.myAttemptCount > 0 && state.playMode === 'BID' ? <div className={state.myAnswerCorrect ? 'notice success' : 'notice info'}>Đã gửi đáp án: <b>{state.myAnswer}</b>. Chờ người khác trả lời.</div> : state.myAnswerCorrect === true ? <div className="notice success">Đã trả lời đúng: <b>{state.myAnswer}</b>. Chờ người khác trả lời.</div> : state.myAttemptCount >= 30 ? <div className="notice info">Bạn đã dùng hết 30 lần thử cho câu này.</div> : <form onSubmit={e => { e.preventDefault(); command('answer', answer); }}><div className="field" style={{ marginTop: 23 }}><label>Đáp án của bạn</label><input ref={answerInputRef} autoFocus disabled={busy} value={answer} maxLength={120} onChange={e => setAnswer(e.target.value)} placeholder={film?"Nhập tên phim":"Nhập tên bài hát"} /></div><button className="button primary big full" disabled={!answer.trim() || busy}>{pendingAction === 'answer' ? 'Đang kiểm tra đáp án…' : 'Gửi đáp án'}</button></form> : <><div className="waiting-art"><Clock3 size={38} /></div><p className="center subtitle">{names(state)} đang trả lời…</p></>}<p className="countline">{answered}/{state.activeChallengerIds.length} {state.playMode === 'OPEN' ? 'đã trả lời đúng' : 'đã gửi đáp án'}</p></div>}
      {state.phase === 'ROUND_RESULT' && (resultVideoOnly ? <div className="panel result-video-only" aria-label="Video công bố đáp án"><div className="result-song"><span>ĐÁP ÁN VÒNG {state.gameRound}</span><h2>{state.question.primaryAnswer}</h2><p>{state.question.artist?.trim() || (film?'':'Chưa cập nhật ca sĩ')}</p></div><ClipPlayer key={`result-${state.questionIndex}`} url={state.question.mediaUrl!} start={Number(state.question.resultStart ?? state.question.mediaStart ?? 0)} duration={Number(state.question.resultSeconds ?? 4)} reveal paused={state.pausedAt !== null} /></div> : <div className="panel"><div className="phase-banner"><span className="phase-pill">KẾT QUẢ VÒNG {state.gameRound}</span><Countdown end={state.phaseEndsAt} pausedAt={state.pausedAt} serverNow={state.serverNow} /></div><h2>Đáp án là</h2><div className="result-answer">{state.question.primaryAnswer}</div><p className="subtitle">{film?'Đạo diễn / diễn viên':'Ca sĩ'}: {state.question.artist?.trim() || 'Chưa cập nhật'}</p><div className="divider" /><PlayerList players={state.players} showScore /><p className="countline">Bảng điểm sẽ tự hiện sau đoạn kết quả.</p>{kind === 'host' && <button className="button primary big" style={{ marginTop: 22 }} disabled={busy} onClick={() => command('showScoreboard')}>Xem bảng điểm ngay <ArrowRight size={18} /></button>}</div>)}
      {(state.phase === 'SCOREBOARD' || state.phase === 'GAME_FINISHED') && <div className="panel"><div className="phase-banner"><span className="phase-pill">{state.phase === 'GAME_FINISHED' ? 'KẾT THÚC' : `BẢNG XẾP HẠNG · VÒNG ${state.gameRound}`}</span>{state.phase === 'SCOREBOARD' && <Countdown end={state.phaseEndsAt} pausedAt={state.pausedAt} serverNow={state.serverNow} />}</div><h2>{state.phase === 'GAME_FINISHED' ? 'Nhà vô địch đã lộ diện!' : 'Điểm hiện tại'}</h2>{state.phase === 'GAME_FINISHED' && state.players[0] && <div className="champion-hero" style={playerStyle(state.players[0])}><span className="champion-medal"><Trophy size={27} /></span><span className="champion-avatar"><PlayerAvatar id={state.players[0].avatarId} size={86} /></span><div><small>HẠNG NHẤT</small><strong>{state.players[0].nickname}</strong><span>{state.players[0].score.toLocaleString('vi-VN')} điểm</span></div></div>}<RankingBoard key={state.questionIndex} players={state.players} finished={state.phase === 'GAME_FINISHED'} />{state.phase === 'SCOREBOARD' && <p className="countline">{state.nextGameRound === null ? 'Trò chơi sẽ tự kết thúc' : state.nextGameRound !== state.gameRound ? `Vòng ${state.nextGameRound} sẽ tự bắt đầu` : 'Câu tiếp theo sẽ tự bắt đầu'} sau ít giây.</p>}{kind === 'host' && state.phase === 'SCOREBOARD' && <button className="button primary big" style={{ marginTop: 25 }} disabled={busy} onClick={() => command('nextQuestion')}>{state.nextGameRound === null ? 'Kết thúc ngay' : state.nextGameRound !== state.gameRound ? `Bắt đầu vòng ${state.nextGameRound} ngay` : 'Sang câu tiếp theo ngay'} <ArrowRight size={18} /></button>}{state.phase === 'GAME_FINISHED' && <Link className="button secondary" style={{ marginTop: 23 }} href="/quizzes">Chơi bộ câu hỏi khác</Link>}</div>}
      {kind === 'host' && !['LOBBY', 'GAME_FINISHED'].includes(state.phase) && <div className="host-actions">{state.phase === 'BIDDING' && <button className="button secondary" onClick={() => command('endBidding')} disabled={busy}>Kết thúc đấu giá</button>}{!['ROUND_RESULT', 'SCOREBOARD'].includes(state.phase) && <button className="button secondary" onClick={() => command('skipQuestion')} disabled={busy}>Bỏ qua câu hỏi</button>}<button className="button danger" onClick={() => { if (confirm('Kết thúc trò chơi ngay?')) command('endGame'); }} disabled={busy}>Kết thúc trò chơi</button></div>}
    </div><aside className="panel game-sidebar"><span className="kicker">NGƯỜI CHƠI TRONG PHÒNG</span><h3>{state.players.length}/4 đã tham gia</h3><PlayerList players={state.players} showScore={false} /></aside></div>
    </div>
  </main>;
}
function LockProgress({ count, total }: { count: number; total: number }) { return <>{count} / {total} người chơi đã chốt thời gian</>; }
function PlayerList({ players, showScore }: { players: RoomPlayer[]; showScore: boolean }) { return <div className="player-list">{players.map(p => <div className="player-row" key={p.id} style={playerStyle(p)}><span className="player-name"><PlayerAvatar id={p.avatarId} size={38} /><span><i className={`status-dot ${p.connected ? 'online' : ''}`} />{p.nickname}</span></span><small>{showScore ? <>{p.correct === true ? <Check size={13} color="#7ee6aa" /> : p.correct === false && p.answerLocked ? <X size={13} color="#ff9b9b" /> : null} {p.bid != null ? `${p.bid}s · ` : ''}{p.correctRank ? `đúng thứ ${p.correctRank} · ` : ''}{p.roundDelta ? `+${p.roundDelta} · ` : ''}{p.score} điểm</> : p.connected ? 'đã vào' : 'mất kết nối'}</small></div>)}</div>; }

